# Generated by Django 4.1 on 2022-08-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categoryName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='imageChallenge',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='titleChallenge',
            field=models.CharField(max_length=500),
        ),
    ]
