# Generated by Django 4.1 on 2022-08-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_alter_categories_categoryname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='isChallenge',
            field=models.BooleanField(default=False),
        ),
    ]
