# Generated by Django 4.1 on 2022-09-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_challenge_ischallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
    ]
