# Generated by Django 3.2.8 on 2021-12-14 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20211212_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='auctionWashlist',
            new_name='auctionWatchlist',
        ),
    ]
