# Generated by Django 3.2.8 on 2021-12-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.CharField(max_length=64),
        ),
    ]
